### ISSUE TITLE
Braid webserver integration to trigger webflows via http

### ISSUE THREAD

**Issue by rogersanick** [rogersanick/corda-accord-template#21]

**Comment by rogersanick** [comment]
https://gitlab.com/bluebank/braid/tree/c2d63754052bfdc786e365d9b82115740c24f095/examples/example-cordapp/cordapp/src/main/kotlin/io/bluebank/braid/corda/example

**Comment by jeromesimeon** [comment]
Is this really done or still on a branch?

**Comment by jeromesimeon** [comment]
A version of the braid integration which works with the latest fixes from master is at https://github.com/rogersanick/corda-accord-template/tree/braidIntegrationToo

**Comment by jeromesimeon** [comment]
This now works and is merged into master.
