### ISSUE TITLE
Calling Cicero parse from Java/Kotlin

### ISSUE THREAD

**Issue by jeromesimeon** [rogersanick/corda-accord-template#8]
What is the best way to call Cicero (for parsing the contract) from Java?

The current approach is through a system call to a shell script:
https://github.com/rogersanick/corda-accord-template/blob/40c06f8bda536efe4ef714276713441f2443f67f/java-source/src/main/java/net/corda/accord/flow/PromissoryNoteIssueFlow.java#L55

But it might be possible to call the cicero engine directly from Java e.g., using Nashorn or GraalVM.

An example of that can be found at https://github.com/mttrbrts/cordapp-example/blob/d6c0f1556fd789ba01030a20f496e88c4fa643cd/kotlin-source/src/main/kotlin/com/example/contract/IOUContract.kt

**Comment by rogersanick** [comment]
Should be closed by #29

**Comment by jeromesimeon** [comment]
Agreed. I'm closing this issue.
